version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
before_build:
- dotnet restore -v Minimal
build_script:
- dotnet --info
- dotnet build **\project.json -c %CONFIGURATION%
after_build:
- dotnet pack src -c %CONFIGURATION%  --version-suffix {build}
artifacts:
- path: src\bin\%CONFIGURATION%
#cache:
#- '%USERPROFILE%\.nuget\packages' -> '**\project.json'
deploy:
  provider: NuGet
  server: https://www.myget.org/F/soda-digital/api/v2/package
  api_key:
    secure: E/HMTks6TaVLFL86uw1NStIvbrHsVrYo2lWnZpa9BVMz32/cYkd1KE9vXdByWTzT
  skip_symbols: true
  artifact: src\bin\%CONFIGURATION%\*\.nupkg