version: 1.0.{build}
os: Visual Studio 2017 RC
configuration: Release
pull_requests:
  do_not_increment_build_number: true
before_build:
- dotnet --info
- dotnet restore -v Minimal
build_script:
- dotnet build -c %CONFIGURATION%
after_build:
- dotnet pack -c %CONFIGURATION%  --version-suffix beta-%APPVEYOR_BUILD_NUMBER% --no-build
artifacts:
- path: src\bin\%CONFIGURATION%\*.nupkg
#cache:
#- '%USERPROFILE%\.nuget\packages -> **\project.json' Cache is actually slower...
deploy:
  provider: NuGet
  server: https://www.myget.org/F/soda-digital/api/v2/package
  api_key:
    secure: E/HMTks6TaVLFL86uw1NStIvbrHsVrYo2lWnZpa9BVMz32/cYkd1KE9vXdByWTzT
  skip_symbols: true
#  artifact: src\bin\%CONFIGURATION%\*\.nupkg